/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.ui.components.swing.displayers;

import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Home
 */
public class Card extends javax.swing.JPanel {

    String imageURL, title, secondaryText, mediaURL, supportText;
    Action mainButtonAction, secundaryButtonAction;

    /**
     * Creates new form LongCard
     *
     * @param imageURL
     * @param title
     * @param secondaryText
     * @param mediaURL
     * @param supportText
     * @param mainButtonAction
     * @param secundaryButtonAction
     */
    public Card(
            String imageURL,
            String title,
            String secondaryText,
            String mediaURL,
            String supportText,
            Action mainButtonAction,
            Action secundaryButtonAction) {
        this.imageURL = imageURL;
        this.title = title;
        this.mediaURL = mediaURL;
        this.supportText = supportText;
        this.mainButtonAction = mainButtonAction;
        this.secundaryButtonAction = secundaryButtonAction;

        initComponents();
        setComponentsInfo();

    }

    public Card(String imageURL,
            String title,
            String secondaryText) {

        this(imageURL, title, secondaryText, null, null, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabelIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCardTitle = MaterialComponentsFactory.Displayers.getH3Label();
        jLabelSecondaryText = MaterialComponentsFactory.Displayers.getLabel();
        jPanelMedia = new javax.swing.JPanel();
        jLabelMedia = new javax.swing.JLabel();
        jPanelSupportText = new javax.swing.JPanel();
        jLabelSupportText = new javax.swing.JLabel();
        jPanelActionButtons = new javax.swing.JPanel();
        jButtonSecondary = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonPrimary = MaterialComponentsFactory.Buttons.getMaterialButton();

        setPreferredSize(new java.awt.Dimension(350, 450));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(250, 100));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanelHeader.setLayout(new javax.swing.BoxLayout(jPanelHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabelIcon.setText("<icon>");
        jLabelIcon.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabelIcon.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabelIcon.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelHeader.add(jLabelIcon);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel2.setMaximumSize(new java.awt.Dimension(30000, 30000));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jLabelCardTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelCardTitle.setText("<Card Title>");
        jLabelCardTitle.setMaximumSize(new java.awt.Dimension(3000, 3000));
        jPanel2.add(jLabelCardTitle);

        jLabelSecondaryText.setText("<Secondary Text>");
        jLabelSecondaryText.setMaximumSize(new java.awt.Dimension(3000, 3000));
        jPanel2.add(jLabelSecondaryText);

        jPanelHeader.add(jPanel2);

        add(jPanelHeader);

        jPanelMedia.setMinimumSize(new java.awt.Dimension(0, 200));
        jPanelMedia.setPreferredSize(new java.awt.Dimension(433, 200));

        jLabelMedia.setText("<Media>");
        jPanelMedia.add(jLabelMedia);

        add(jPanelMedia);

        jPanelSupportText.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelSupportText.setMinimumSize(new java.awt.Dimension(0, 50));

        jLabelSupportText.setText("<Support Text>");
        jPanelSupportText.add(jLabelSupportText);

        add(jPanelSupportText);

        jPanelActionButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelActionButtons.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanelActionButtons.setPreferredSize(new java.awt.Dimension(169, 25));
        jPanelActionButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonSecondary.setText("jButton1");
        jPanelActionButtons.add(jButtonSecondary);

        jButtonPrimary.setText("jButton2");
        jPanelActionButtons.add(jButtonPrimary);

        add(jPanelActionButtons);
    }// </editor-fold>//GEN-END:initComponents

    private void setComponentsInfo() {

        if (imageURL == null) {
            jLabelIcon.setVisible(false);
        } else {
            jLabelIcon.setIcon(circlarShape(imageURL));
        }
        if (title == null) {
            jLabelCardTitle.setVisible(false);
        } else {
            jLabelCardTitle.setText(title);
        }
        if (secondaryText == null) {
            jLabelSecondaryText.setVisible(false);
        } else {
            jLabelSecondaryText.setText(secondaryText);
        }
        if (mediaURL == null) {
            jLabelMedia.setVisible(false);
        } else {
            jLabelMedia.setIcon(new javax.swing.ImageIcon(mediaURL));
        }
        if (supportText == null) {
            jLabelSupportText.setVisible(false);
        } else {
            jLabelSupportText.setText(supportText);
        }
        if (mainButtonAction == null) {
            jButtonPrimary.setVisible(false);
        } else {
            jButtonPrimary.setAction(mainButtonAction);
        }
        if (secundaryButtonAction == null) {
            jButtonSecondary.setVisible(false);
        } else {
            jButtonSecondary.setAction(secundaryButtonAction);
        }
    }

    public ImageIcon circlarShape(String image) {

        try {
            BufferedImage master = ImageIO.read(new File(image));

            int diameter = Math.min(master.getWidth(), master.getHeight());
            BufferedImage mask = new BufferedImage(master.getWidth(), master.getHeight(), BufferedImage.TYPE_INT_ARGB);

            Graphics2D g2d = mask.createGraphics();
            applyQualityRenderingHints(g2d);
            g2d.fillOval(0, 0, diameter - 1, diameter - 1);
            g2d.dispose();

            BufferedImage masked = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
            g2d = masked.createGraphics();
            applyQualityRenderingHints(g2d);
            int x = (diameter - master.getWidth()) / 2;
            int y = (diameter - master.getHeight()) / 2;
            g2d.drawImage(master, x, y, null);
            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.DST_IN));
            g2d.drawImage(mask, 0, 0, null);
            g2d.dispose();

            return new ImageIcon(masked);
        } catch (IOException ex) {
            Logger.getLogger(Card.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public static void applyQualityRenderingHints(Graphics2D g2d) {

        g2d.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrimary;
    private javax.swing.JButton jButtonSecondary;
    private javax.swing.JLabel jLabelCardTitle;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelMedia;
    private javax.swing.JLabel jLabelSecondaryText;
    private javax.swing.JLabel jLabelSupportText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelActionButtons;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMedia;
    private javax.swing.JPanel jPanelSupportText;
    // End of variables declaration//GEN-END:variables
}
