/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.ui.components.swing.displayers;

import com.jobits.ui.components.swing.containers.MaterialPanel;
import components.labels._MaterialLabel;
import components.progress._MaterialProgressSpinner;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JLabel;
import ui.componentsui.progressbar.MaterialProgressBarUI;
import util.materials.MaterialFontRoboto;

/**
 *
 * @author Jorge
 */
public class LoadingPanel extends MaterialPanel {

    String msg = "Cargando...";

    public LoadingPanel() {
        init();
    }

    public LoadingPanel(String loadingMessage) {
        msg = loadingMessage;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(250, 120));
        setMinimumSize(new java.awt.Dimension(250, 120));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(250, 120));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        initComponents();
        Box.Filler fix1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        _MaterialProgressSpinner spinner = new _MaterialProgressSpinner();
        spinner.setPreferredSize(new Dimension(50, 50));
        Box.Filler filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        JLabel label = new _MaterialLabel();
        label.setFont(MaterialFontRoboto.BOLD);
        label.setText(msg);
        Box.Filler fix2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        add(fix1);
        add(spinner);
        add(filler1);
        add(label);
        add(fix2);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
