/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.ui.components.swing.containers;

import com.jobits.pos.ui.DefaultValues;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXCollapsiblePane;

/**
 *
 * @author Jorge
 */
//TODO: el tooltip funciona raro
//TODO: popup panel para cuando esta encogido el panel
//TODO: hacerlo personalizable el string de la cantidad
//TODO: crear un collapse menu que sea solo y no tenga submenu
//TODO: fondo personalizable
//TODO: 
public class CollapseMenu extends JPanel {

    public static final String PROP_COLLAPSE = "Collapse";

    private Icon iconoCategoria;
    private String nombreCategoria;

    public CollapseMenu(Icon iconoCategoria,
            String nombreCategoria) {
        initComponents();
        this.iconoCategoria = iconoCategoria;
        this.nombreCategoria = nombreCategoria;
        configurateUI();

    }

    /**
     * @Deprecated no usar porque no funciona muy bien con el popup
     * @param item
     */
    public void addMenuItem(Component item) {
        jPanelSubActions.add(item);
        jPopupMenu1.add(item);
        jLabel1.setText("" + jPanelSubActions.getComponentCount());
    }

    public Component addMenuItem(Action action) {
        Component c = jPanelSubActions.add(buildFromAction(action));
        jLabel1.setText("" + jPanelSubActions.getComponentCount());
        jPopupMenu1.add(action);
        return c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSubActions = new org.jdesktop.swingx.JXTaskPaneContainer();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanelFixed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonIcono = new javax.swing.JButton();
        jButtonNombre = new javax.swing.JButton();
        jPanelCollapsible = new org.jdesktop.swingx.JXCollapsiblePane();

        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jPanelSubActions.setLayout(verticalLayout1);

        setMinimumSize(new java.awt.Dimension(90, 90));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanelFixed.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFixed.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        jPanelFixed.setMinimumSize(new java.awt.Dimension(327, 60));
        jPanelFixed.setOpaque(false);
        jPanelFixed.setPreferredSize(new java.awt.Dimension(294, 60));
        jPanelFixed.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("#");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanelFixed.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jButtonIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIcono.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonIcono.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonIcono.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanelFixed.add(jButtonIcono, java.awt.BorderLayout.LINE_START);

        jButtonNombre.setFont(new java.awt.Font(".SF NS Text", 0, 18)); // NOI18N
        jButtonNombre.setText("<Nombre>");
        jButtonNombre.setBorderPainted(false);
        jPanelFixed.add(jButtonNombre, java.awt.BorderLayout.CENTER);

        add(jPanelFixed, java.awt.BorderLayout.PAGE_START);

        jPanelCollapsible.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 60, 10, 1));
        jPanelCollapsible.setDirection(org.jdesktop.swingx.JXCollapsiblePane.Direction.DOWN);
        jPanelCollapsible.setOpaque(false);
        add(jPanelCollapsible, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void shrink() {
        onMouseCLicked();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIcono;
    private javax.swing.JButton jButtonNombre;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXCollapsiblePane jPanelCollapsible;
    private javax.swing.JPanel jPanelFixed;
    private org.jdesktop.swingx.JXTaskPaneContainer jPanelSubActions;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

    private Component buildFromAction(Action a) {
        return new TaskButton(a, jPanelSubActions.getWidth());
    }

    private void configurateUI() {
        jPanelCollapsible.setLayout(new BorderLayout());
        jPanelCollapsible.add(jPanelSubActions, BorderLayout.CENTER);
        jButtonIcono.setText("");
        jButtonIcono.setIcon(iconoCategoria);
        jButtonIcono.setBorderPainted(false);
        jButtonIcono.setContentAreaFilled(false);
        jButtonNombre.setText(nombreCategoria);
        jButtonNombre.setContentAreaFilled(false);
        jButtonNombre.setBorderPainted(false);
        setBackground(DefaultValues.SECONDARY_COLOR);
        
        jPanelCollapsible.addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if (evt.getPropertyName().equals("collapse")) {
                setOpaque(!jPanelCollapsible.isCollapsed());
            }
        });
        jButtonIcono.addActionListener((ActionEvent e) -> {
            onMouseCLicked();
        });
        jButtonNombre.addActionListener((ActionEvent e) -> {
            onMouseCLicked();
        });

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                super.componentResized(e); //To change body of generated methods, choose Tools | Templates.
                if (isShinked()) {
                    jPanelCollapsible.setCollapsed(true);
                    jButtonIcono.setToolTipText(nombreCategoria);

                } else {
                    jButtonIcono.setToolTipText("");
                }

            }

        });

    }

    private boolean isShinked() {
        return getSize().width < 85;//TODO: personalizar tamanno del menu
    }

    private void createPopupPanel() {
        jPopupMenu1.show(this, jButtonIcono.getBounds().x + jButtonIcono.getWidth(), jButtonIcono.getBounds().y);
        //  Logger.getLogger(getClass().getName()).log(Level.WARNING, "En desarrollo");
    }

    private void onMouseCLicked() {
        if (isShinked()) {
            createPopupPanel();
        } else {
            jPanelCollapsible.getActionMap().get(JXCollapsiblePane.TOGGLE_ACTION).actionPerformed(null);
        }

    }

}
