/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.ui.components.swing.containers;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXCollapsiblePane;
import org.jdesktop.swingx.JXTaskPaneContainer;
import org.jdesktop.swingx.VerticalLayout;

/**
 *
 * @author Jorge
 */
public class CollapseMenu extends JPanel {

    public static final String PROP_COLLAPSE = "Collapse";

    private Icon iconoCategoria;
    private String nombreCategoria;

    public CollapseMenu(Icon iconoCategoria,
            String nombreCategoria) {
        initComponents();
        this.iconoCategoria = iconoCategoria;
        this.nombreCategoria = nombreCategoria;
        configurateUI();

    }

    public void addMenuItem(Component item) {
        jPanelSubActions.add(item);
        jLabel1.setText("" + jPanelSubActions.getComponentCount());
    }

    public Component addMenuItem(Action action) {
        Component c = jPanelSubActions.add(buildFromAction(action));
        jLabel1.setText("" + jPanelSubActions.getComponentCount());
        return c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSubActions = new org.jdesktop.swingx.JXTaskPaneContainer();
        jPanelFixed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jPanelCollapsible = new org.jdesktop.swingx.JXCollapsiblePane();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 5));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanelFixed.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFixed.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        jPanelFixed.setMinimumSize(new java.awt.Dimension(327, 60));
        jPanelFixed.setOpaque(false);
        jPanelFixed.setPreferredSize(new java.awt.Dimension(294, 60));
        jPanelFixed.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("#");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanelFixed.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabelNombre.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("<Nombre Categoria>");
        jLabelNombre.setPreferredSize(new java.awt.Dimension(134, 60));
        jPanelFixed.add(jLabelNombre, java.awt.BorderLayout.CENTER);

        jLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcono.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelIcono.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabelIcono.setSize(new java.awt.Dimension(60, 60));
        jPanelFixed.add(jLabelIcono, java.awt.BorderLayout.LINE_START);

        add(jPanelFixed, java.awt.BorderLayout.PAGE_START);

        jPanelCollapsible.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 60, 10, 1));
        jPanelCollapsible.setDirection(org.jdesktop.swingx.JXCollapsiblePane.Direction.DOWN);
        jPanelCollapsible.setOpaque(false);
        add(jPanelCollapsible, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelNombre;
    private org.jdesktop.swingx.JXCollapsiblePane jPanelCollapsible;
    private javax.swing.JPanel jPanelFixed;
    private org.jdesktop.swingx.JXTaskPaneContainer jPanelSubActions;
    // End of variables declaration//GEN-END:variables

    private Component buildFromAction(Action a) {
        return new TaskButton(a,jPanelSubActions.getWidth());
    }

    private void configurateUI() {
        jPanelCollapsible.setLayout(new BorderLayout());
        jPanelCollapsible.add(jPanelSubActions, BorderLayout.CENTER);
        jLabelIcono.setText("");
        jLabelIcono.setIcon(iconoCategoria);
        jLabelNombre.setText(nombreCategoria);
        //setBackground(new Color(255, 255, 255, 40));

        jPanelCollapsible.addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if (evt.getPropertyName().equals("collapse")) {
                setOpaque(!jPanelCollapsible.isCollapsed());
            }
        });
        jPanelFixed.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                onMouseClicked(e);
            }

        });
        jLabelIcono.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                onMouseClicked(e);
            }

        });

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                super.componentResized(e); //To change body of generated methods, choose Tools | Templates.
                if (isShinked()) {
                    jPanelCollapsible.setCollapsed(true);
                }
            }

        });

    }

    private boolean isShinked() {
        return getSize().width < 70;
    }

    private void createPopupPanel(MouseEvent e) {
        Logger.getLogger(getClass().getName()).log(Level.WARNING, "En desarrollo");
    }

    private void onMouseClicked(MouseEvent e) {
        if (isShinked()) {
            createPopupPanel(e);
        } else {
            jPanelCollapsible.getActionMap().get(JXCollapsiblePane.TOGGLE_ACTION).actionPerformed(null);
        }
        jLabelIcono.setToolTipText(isShinked() ? nombreCategoria : "");

    }

}
